### ISSUE TITLE
Rubric

### ISSUE THREAD

**Issue by KseniaZhe** [KseniaZhe/ksnz.ca#1]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & sections** | Barely started | Missing lots of sections/pages | Has most of the sections/pages, some missing | All sections/pages exist and are well done |
| **Personality** | Bland, boring, just another graphic designer | Fairly generic but may be better with visual design | Quality layouts and unique, personable content | Unique and recognizable as you, with engaging, personable content |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

**Comment by KseniaZhe** [comment]
Pages & sections: 3 points. The home page and one porfolio piece page are well done.
Personality: 3 points. Unique and recognizable as you, with engaging, personable content.
Text content: 3 points. Real content, well written, no grammar or spelling errors
Responsiveness: 3 points. Looks great on all screen sizes.
Code quality: 3 points. Used classes and groups. awesome.

**Comment by digitalsara** [comment]
Pages & Sections: 3 points - Great divisions in your pages. Love the animation you have going on!
Personality: 3 points - I can totally know it's your website! Sophisticated and memorable.
Text content: 3 points - All real content, no placeholders.
Responsiveness: 3 points - Responsive across all sizes. Great!
Code quality: 3 points - Used appropriate classes and semantics.

Total 15 points

**Comment by catherine9** [comment]
Pages & section: 3 points love the animation when you hover over it 
Personality 3 points, Website is clean and nice. Very Ksenia 
Text content 3 point, Love the font choice used, love the content
Responsiveness: 3 point very responsive on all sizes
Code quality: 3 points classes and divs are used nicely
