### ISSUE TITLE
Compress Transfer Issue

### ISSUE THREAD

**Issue by digitalsara** [KseniaZhe/ksnz.ca#10]
Hey Ksenia! webpagetest failed Compress Transfer for this particular image:

`http://ksnz.ca/images/zh.cur`

And gives a warning for this script:

`http://ksnz.ca/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js`

**Comment by KseniaZhe** [comment]
hm.... Interesting... I have to check that. Thank you! :)
