### ISSUE TITLE
Nov 21: Peer Evaluation

### ISSUE THREAD

**Issue by KseniaZhe** [KseniaZhe/ksnz.ca#4]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | All pages exist and are well done with complete imagery |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | Unique and recognizable as you, with engaging, personable content & design |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | High quality portfolio images — and lots of them |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

**Comment by catherine9** [comment]
**Pages & images** 3points- All the pages exist and and is laid out very nicely
**Personality & design** 3points- VERY UNIQUE, very ksenia on from home page to each portfolio page
**Image quality** 3 points-images a very sharp and clean, mockups are nicely done 
**Accessibility** 3 points- Very accessible
**Text content** 3 points- No grammatical or spelling errors
**Responsiveness** 3 points- Very responsive
**Code quality** 3 points- Code is very good and well indented

**Comment by digitalsara** [comment]
Pages & Images: 3pts
Personality & design: 3pts
Image quality: 3pts
Accessibility: 3pts
Text content: 3pts
Responsiveness: 3pts
Code quality: 3pts

Total: 21/21

Overall, wonderful website! Love the layout and your style. Only thing is watch out for slow-loading banners, smush smush smush! ;)

**Comment by mpelletiervaillant-zz** [comment]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | **All pages exist and are well done with complete imagery** |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | **Unique and recognizable as you, with engaging, personable content & design** |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | **High quality portfolio images — and lots of them** |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | **Accessibility is well considered and tested** |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | **Looks great on all screen sizes** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

Beautiful Ksenia! The best I've seen! 
Minor suggestions: adding buttons to next project, adding padding to bottom of images at the end of the pages
