### ISSUE TITLE
Browser Testing-Firefox

### ISSUE THREAD

**Issue by saradactyl27** [KseniaZhe/ksnz.ca#8]
Compact Music Header:
- the text gets lost in the background image on some screen sizes (the whites blend together)
Hooray:
- header text gets lost in the balloon animal same as the other one
- Kerning looks off on "Idea for an App" (the I and d) is there an extra space or is it just the font?

The Manticore:
- last image is super blurry

- The page navigation buttons on your pages are a little glitchy on large screens. The button moves over a lot and throws off the target area of the mouse
- responsivness is great
- I love the layout

**Comment by KseniaZhe** [comment]
Interesting... I will have to check that. Thank you!
